#!/usr/bin/env ruby
# encoding: UTF-8

reset = "\r\e[K"

STDOUT.sync = true
print '         ┳━┳     '
sleep 1
print reset
print '°-°)     ┳━┳     '
sleep 1
print reset
print '(ヽ°-°)ヽ┳━┳     '
sleep 1
print reset
print '(╯ °□°）╯︵ ┻━┻  '
sleep 1
print reset
print ' (°-° )     ┻━┻  '
sleep 1
print reset
print '-° )        ┻━┻  '
sleep 1
print reset
print '            ┻━┻  '
sleep 1
print "\n"
