#!/usr/bin/env ruby
# encoding: UTF-8

reset = "\r\e[K"

STDOUT.sync = true
print '(ヽ°-°)ヽ┳━┳'
sleep 1
print reset
print '(╯ °□°）╯︵ ┻━┻'
sleep 1
print 'ﾉ(°-°ﾉ)     ┻━┻'
sleep 1
print '-°ﾉ)        ┻━┻'
sleep 1
print '            ┻━┻'
sleep 1
print "\n"
